ALTER TABLE deltas
  ADD COLUMN IF NOT EXISTS delta_1m DOUBLE PRECISION;

ALTER TABLE deltas
  ADD COLUMN IF NOT EXISTS delta_5m DOUBLE PRECISION;

ALTER TABLE deltas
  ADD COLUMN IF NOT EXISTS delta_10m DOUBLE PRECISION;

